dist: trusty
language: rust
sudo: false
rust: stable
compiler:
  - gcc
  - clang
script:
  - rustup target add i586-unknown-linux-gnu
  - cargo build
  - cargo test
  - cargo test --release
  - cargo test --target i586-unknown-linux-gnu --release
