dist: trusty
language: rust
sudo: false
rust: stable
addons:
  apt:
    packages:
      - gcc-multilib
      - g++-multilib
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry
matrix:
  include:
    - env: CC=clang CXX=clang++
    - env: CC=gcc CXX=g++
    - env: CC=gcc-8 CXX=g++-8
      addons:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-8-multilib
          - g++-8-multilib
script:
  - rustup target add i586-unknown-linux-gnu
  - cargo build
  - cargo test
  - cargo test --release
  - cargo test --target i586-unknown-linux-gnu --release
